name: develop action

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r develop-requirements.txt
      - name: Check mypy
        run: python -m mypy nmcli
      - name: Check lint
        run: python -m pylint nmcli
      - name: Run unit tests
        run: python -m pytest tests
